### ISSUE TITLE
Simplify the nested directory structure generated by tmaDearray()

### ISSUE THREAD

**Issue by ArtemSokolov** [HMS-IDAC/batchtmaDearray#1]
I am working on integrating Coreograph into an automated pipeline workflow. When running this command:

``` matlab
tmaDearray('~/test/exemplar-002/registration/stitched.ome.tif',...
       'outputPath','~/test/exemplar-002/dearray','useGrid','true')
```

I expect that the individual core files would be placed in the folder I specified in the `outputPath` (i.e, `~/test/exemplar-002/dearray`). However, the function seems to create additional nested folder structure and places files in `/home/sokolov/test/exemplar-002/dearray/stitched/dearray` instead.

I think the problem is at https://github.com/HMS-IDAC/Coreograph/blob/e21b137e9bde2b95f0402836bd9bb2658f436aea/TMAsegmentation/tmaDearray.m#L134
which should just be:
``` matlab
writePath = p.outputPath;
```
instead.

**Comment by ArtemSokolov** [comment]
I mentioned to @clarenceyapp that the subdirectory creation can be moved up to the `batchtmaDearray()` script, which iterates over all stitched images in a project. Since it has an overall view of the project, the batch script is in a better position to handle the subdirectory structure.

So, the appending of `filePrefix filesep 'dearray'` can potentially live right before the `tmaDearray()` call:

https://github.com/HMS-IDAC/Coreograph/blob/e21b137e9bde2b95f0402836bd9bb2658f436aea/TMAsegmentation/batchtmaDearray.m#L62

**Comment by clarenceyapp** [comment]
outputPath has been moved to the level of batch function as suggested.
